export const smapleTitle1 = 'The Importance of Title and Paragraphs in Writing';

export const simpleText =
  'Titles and paragraphs are essential elements of good writing. They help to organize the text, make it easier to read, and highlight the key points. A good title should be clear, concise, and attention-grabbing. It should give the reader a good idea of what the text is about.';

export const originText =
  '<p>Titles and paragraphs are <em>essential</em> elements of good writing. They help to organize the text, make it easier to read, and highlight the key points.</p><br /><p>A good title should be <em>clear</em>, <em>concise</em>, and attention-grabbing. It should give the reader a good idea of what the text is about.</p>';

export const originText2 = `<h1><span style=\"color: rgb(0, 0, 0);\">Heading1</span></h1>\n<h2><span style=\"color: rgb(0, 0, 0);\">Heading2</span></h2>\n<h3><span style=\"color: rgb(0, 0, 0);\">Heading3</span></h3>\n<h4><span style=\"color: rgb(0, 0, 0);\">Heading4</span></h4>\n<h5><span style=\"color: rgb(0, 0, 0);\">Heading5</span></h5>\n<h6><span style=\"color: rgb(0, 0, 0);\">Heading6</span></h6>\n<blockquote>\n<p><span style=\"color: rgb(0, 0, 0);\"><strong>Lorem Ipsum</strong> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span></p>\n</blockquote>\n<p style=\"text-align: center;\"><span style=\"color: rgb(0, 0, 0);\">あいうえおえ</span><br><br><span style=\"color: rgb(0, 0, 0);\"><strong><em>さしすせそ<br></em><br><br>なにぬねの</strong></span></p>\n<p style=\"text-align: center;\"><span style=\"color: rgb(230, 126, 35);\"><strong>まみむめも</strong></span></p>\n<p><span style=\"color: rgb(0, 0, 0);\"><span style=\"color: rgb(45, 194, 107);\"><strong>やゆよ</strong></span></span></p>\n<ul>\n<li><span style=\"color: rgb(0, 0, 0);\"><strong>リストアイテム1</strong></span></li>\n<li><strong>リストアイテム2</strong></li>\n<li><strong>リストアイテム3</strong></li>\n</ul>\n<p>&nbsp;</p>\n<ul style=\"list-style-type: circle;\">\n<li><span style=\"color: rgb(0, 0, 0);\"><strong>リストアイテム1</strong></span></li>\n<li><strong>リストアイテム2</strong></li>\n<li><strong>リストアイテム3</strong></li>\n</ul>\n<ol>\n<li><span style=\"color: rgb(0, 0, 0);\"><strong>Orderリストアイテム1</strong></span></li>\n<li style=\"color: rgb(241, 196, 15);\"><span style=\"color: rgb(241, 196, 15);\"><strong>Orderリストアイテム2</strong></span></li>\n<li><strong>Orderリストアイテム3</strong></li>\n</ol>\n<p><a href=\"https://www.google.com/\"><strong>リンクリンク</strong></a></p>\n<p>&nbsp;</p>`;
